# Generated by Django 3.2.16 on 2022-12-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0005_alter_topic_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('digest', models.CharField(max_length=300, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('page_view', models.IntegerField(default=0, verbose_name='浏览量')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '发布')], default=0, verbose_name='状态')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
                'ordering': ['-priority', '-page_view', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('level', models.IntegerField(default=1, verbose_name='评论等级')),
                ('parent_comment', models.IntegerField(blank=True, null=True, verbose_name='父级评论')),
                ('reply_comment', models.IntegerField(blank=True, null=True, verbose_name='回复评论')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
                'ordering': ['-create_time'],
            },
        ),
    ]
