# Generated by Django 3.2.16 on 2022-11-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='班级名'),
        ),
    ]
