# Generated by Django 3.2.16 on 2022-11-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='desciption',
            new_name='description',
        ),
    ]
