# Generated by Django 3.2.16 on 2022-11-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_rename_desciption_topic_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='label',
            table='labelDetail',
        ),
    ]
