# Generated by Django 3.2.16 on 2022-11-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_label_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='label',
            table='label',
        ),
    ]
